---
- name: Testing...
  hosts: localhost
  connection: local
  become: true
  become_user: root
  become_method: sudo

  vars:
    redis_version: 2.6.16

  tasks:
  - name: Install all apt-packages
    apt: name={{item}} state=present
    with_items:
                - locate
                - vmfs-tools 
                - vmware-manager 
                - vim  
                - virtualbox  
                - virtualbox-ext-pack  
                - gnome-system-tools
                  # - linux-headers 
                - build-essential 
                - dkms 
                - qterminal 
                - firefox 
                - htop 
                - autojump 
                - mc 
                - zsh 
                - tmux 
                - git 
                - powerline 
                - python3 
                - python3-pip 
                - python3-setuptools 
                - python3-dev 
                - python3-tk
                - python-tk
                - python3.6 
                - python3.6-dev 
                - python3.6-tk 
                - virtualenv 
                - virtualenvwrapper 
                - libncurses5-dev 
                - libgdbm-dev 
                - libnss3-dev 
                - libssl-dev 
                - libreadline-dev 
                - libffi-dev 
                - sqlite
                - sqlite3
                - tk8.6
                - tk8.6-dev
                - ansible

  - name: Download Redis
    shell: creates=/tmp/redis-$redis_version wget -O - http://download.redis.io/releases/redis-$redis_version.tar.gz | tar -xz -C /tmp

  - name: Install Redis
    command: creates=/usr/local/bin/redis-server chdir=/tmp/redis-$redis_version make install
    sudo: yes

  - name: Create user redis
    user: name=redis system=yes home=/var/lib/redis shell=/bin/false
    sudo: yes

  - name: Configure Upstart for Redis
    copy: src=files/upstart_redis.conf dest=/etc/init/redis.conf
    sudo: yes
    notify: Restart Redis

  handlers:
    - name: Restart Redis
      service: name=redis state=restarted
      sudo: yes
