---

- name: Setting up VMs ...
  hosts:  localhost # or ubuntu, see hosts.ini
  connection: local
  become: true
  become_user: root
  become_method: sudo

  roles:
          # - role: python # Python3 setup
          - role: docker # Docker setup
          # - role: java  # Java setup, see java/tasks/main.yml
          # - role: odl # ODL setup
          # - role: opendaylight
          # extra_features: ['odl-netvirt-openstack']

  
  vars_files:
          - config.yml
  tasks:
  - name: Accessing variables in inventory file
    debug:
            msg: "Setting up the following host: {{ ansible_host }}"

  - name: Get the links correct
    file:
        src: "{{ dot_dir }}/{{ item }}"
        dest: "{{ user_home_dir }}/.{{ item }}"
        state: link
        force: true
    become: true
    become_user: "{{ username }}"
    with_items: "{{ link_files }}"

  - name: Install all apt-packages
    apt: name={{item}} state=present
    with_items: "{{ apt_packages }}"
    
  - name: Add folders to autojump
    become_user: "{{ username }}"
    command: "autojump --add {{ item }}"
    with_items: "{{ course_folders }}"

 
