---

- name: Testing...
  hosts: localhost
  connection: local
  become: true
  become_user: root
  become_method: sudo


  tasks:
  - name: Install all apt-packages
    apt: name={{item}} state=present
    with_items:
                - locate
                - vmfs-tools 
                - vmware-manager 
                - vim  
                - virtualbox  
                - virtualbox-ext-pack  
                - gnome-system-tools
                  # - linux-headers 
                - build-essential 
                - dkms 
                - qterminal 
                - firefox 
                - htop 
                - autojump 
                - mc 
                - zsh 
                - tmux 
                - git 
                - powerline 
                - python3 
                - python3-pip 
                - python3-setuptools 
                - python3-dev 
                - python3-tk
                - python-tk
                - python3.6 
                - python3.6-dev 
                - python3.6-tk 
                - virtualenv 
                - virtualenvwrapper 
                - libncurses5-dev 
                - libgdbm-dev 
                - libnss3-dev 
                - libssl-dev 
                - libreadline-dev 
                - libffi-dev 
                - sqlite
                - sqlite3
                - tk8.6
                - tk8.6-dev
                - ansible


