username: bh
vm_host_dir: "/media/sf_caumont/"
user_home_dir: "/home/{{ username }}/"
db_dir: "{{ vm_host_dir }}/Dropbox"
vm_host_name: "WHOTRSURFACE20"
dot_dir: "{{ db_dir }}/Dotfiles/{{ vm_host_name }}"
eigene_dir: "{{ db_dir }}/EigeneDateien"
et_dir: "{{ eigene_dir }}/7_Professional/ExperTeach/"
et_course_dir: "{{ et_dir }}/ET_Courses/"
link_files:
        - vimrc
        - bashrc
        - tmux.conf
        - vim
        - jupyter
        - powerline
        - pip_download_cache

python3_version: 3.7.2
python3_url: "https://www.python.org/ftp/python/{{ python3_version }}/Python-{{ python3_version }}.tgz"
python3_install_dir: "/tmp/Python-{{ python3_version }}"
virtenvwrapper_script: "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
python27: "/usr/bin/python2.7"
python36: "/usr/bin/python3.6"
python37: "/usr/bin/python3.7"
virtualenv_dir: "{{ user_home_dir }}/.virtualenvs"
course_folders:
        - "{{ et_course_dir }}/PYFE/pyfe_latest"
        - "{{ et_course_dir }}/BIGD/bigd_latest"
        - "{{ et_course_dir }}/KIML/kiml_latest"
        - "{{ et_course_dir }}/PRPN/prpn_latest"
        - "{{ et_course_dir }}/PRFN/prfn_latest"
        - "{{ et_course_dir }}/PYTH/pyth_latest"
req_dir: "requirements"
virtualenvs: 
    - {name: "Testing3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_testing37.txt"}
    - {name: "Default3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_default37.txt"}
    - {name: "KIML3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_kiml37.txt"}
    - {name: "PYFE3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_pyfe37.txt"}
    - {name: "PRPN3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_prpn37.txt"}
    - {name: "BIGD3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_bigd37.txt"}
    - {name: "PYDA3.7", interpreter: "{{ python37 }}", 
       rfile: "{{ req_dir }}/requirements_pyda37.txt"}
    - {name: "KIML3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_kiml36.txt"}
    - {name: "PYFE3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_pyfe36.txt"}
    - {name: "PRPN3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_prpn36.txt"}
    - {name: "BIGD3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_bigd36.txt"}
    - {name: "PYDA3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_pyda36.txt"}
    - {name: "Default3.6", interpreter: "{{ python36 }}", 
       rfile: "{{ req_dir }}/requirements_default36.txt"}
    - {name: "Default2.7", interpreter: "{{ python27 }}", 
       rfile: "{{ req_dir }}/requirements_default27.txt"}
setup_dir: "setup_ubuntu18"
