username: bh
install_py37_source: false # true
vm_host_dir: "/media/sf_caumont/"
user_home_dir: "/home/{{ username }}/"
db_dir: "{{ vm_host_dir }}/Dropbox"
vm_host_name: "WHOTRSURFACE20"
dot_dir: "{{ db_dir }}/Dotfiles/{{ vm_host_name }}"
eigene_dir: "{{ db_dir }}/EigeneDateien"
et_dir: "{{ eigene_dir }}/7_Professional/ExperTeach/"
et_course_dir: "{{ et_dir }}/ET_Courses/"
ssh_folder: "/etc/ssh/"
ssh_user_folder: "{{ user_home_dir }}/.ssh/"
ssh_rsa_file: "ssh_host_rsa_key"
ssh_dsa_file: "ssh_host_dsa_key"
ssh_ecdsa_file: "ssh_host_ecdsa_key"
imagemagick_version: "7.0.8-26"
imagemagick_url: "https://www.imagemagick.org/download/ImageMagick-{{ imagemagick_version }}.tar.gz"
imagemagick_install_dir: "/tmp/ImageMagick-{{ imagemagick_version }}"
install_imagemagick_source: true

link_files:
        - vimrc
        - bashrc
        - tmux.conf
        - vim
        - jupyter
        - powerline
        - pip_download_cache
        - m2 # maven directory with settings.xml

course_folders:
        - "{{ et_course_dir }}/PYFE/pyfe_latest"
        - "{{ et_course_dir }}/BIGD/bigd_latest"
        - "{{ et_course_dir }}/KIML/kiml_latest"
        - "{{ et_course_dir }}/PRPN/prpn_latest"
        - "{{ et_course_dir }}/PRFN/prfn_latest"
        - "{{ et_course_dir }}/PYTH/pyth_latest"
setup_dir: "setup_ubuntu18"

apt_packages: 
    - locate 
    - cmake  
    - g++  
    - gfortran  
    - pkg-config  
    - tree
    - maven
    - r-base # install R 
    - scala # install Scala 
    - software-properties-common  
    - wget 
    - vmfs-tools  
    - vmware-manager  
    - vim   
    - virtualbox   
    - virtualbox-ext-pack   
    - gnome-system-tools 
    - build-essential  
    - libncurses5-dev 
    - libgdbm-dev 
    - libnss3-dev  
    - default-jdk 
    - libssl-dev  
    - libreadline-dev  
    - libffi-dev 
    - dkms  
    - qterminal  
    - firefox  
    - htop  
    - autojump  
    - mc  
    - zsh  
    - tmux  
    - git  
    - powerline  
    - libncurses5-dev  
    - libgdbm-dev  
    - libnss3-dev  
    - libssl-dev  
    - libreadline-dev  
    - libffi-dev  
    - sqlite 
    - sqlite3 
    - ansible 
    - wireshark 
    - mininet
    - tshark 
    - xsnow
    - openssh-server
    - sshpass
    - expect
    - texlive
    - texlive-base
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-lang-english
    - texlive-lang-german
    - texlive-extra-utils
    - texlive-font-utils
    - texlive-fonts-extra
    - texlive-bibtex-extra
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-xetex
    - texlive-pstricks
    - texlive-science
    - snmpd 
    - snmptt
    - snmp 
    - libsnmp-dev
    - snmp-mibs-downloader
    - snmptrapd
    - sysstat
    - glances
    - gedit
    - network-manager-l2tp
    - network-manager-gnome
    - asciinema  
    - font-manager
    - ttf-mscorefonts-installer
    - emacs25
    - ctags
